name: new Release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Push Container Image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          dockerfile: Dockerfile
          repository: ${{ github.event.repository.full_name }}
          tag_with_ref: true
          tag_with_sha: true

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Open PR in Environment Repository for new App Version
        env:
          ENV_REPO: gitops-tech/example-environment
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: New Application Version
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          inputs: '{"tag_name": "${{ github.event.release.tag_name }}", "app_repo": "${{ github.event.repository.name }}", "image": "${{ github.event.repository.full_name }}:${{ github.event.release.tag_name }}"}'
          ref: refs/heads/master
          repo: ${{ env.ENV_REPO }}
